/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticationImport } from './routes/_authentication'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const AuthenticationSigninLazyImport = createFileRoute(
  '/_authentication/signin',
)()

// Create/Update Routes

const AuthenticationRoute = AuthenticationImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationSigninLazyRoute = AuthenticationSigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => AuthenticationRoute,
} as any).lazy(() =>
  import('./routes/_authentication/signin.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authentication': {
      preLoaderRoute: typeof AuthenticationImport
      parentRoute: typeof rootRoute
    }
    '/_authentication/signin': {
      preLoaderRoute: typeof AuthenticationSigninLazyImport
      parentRoute: typeof AuthenticationImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticationRoute.addChildren([AuthenticationSigninLazyRoute]),
])

/* prettier-ignore-end */
